spring:
  redis:
    database: 1
    password: ENC(PEA4EoxWt3wDw9PS1YDQpJEk/wG1hgbF)
    cluster:
      nodes:
       - 119.23.24.1:6179
       - 119.23.24.1:6279
       - 119.23.24.1:6379
       - 119.23.24.1:6479
       - 119.23.24.1:6579
       - 119.23.24.1:6679
      max-redirects: 3
    timeout: 5000
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制)
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）