spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jbdc:mysql://localhost:3306/jeeplateform?serverTimezone=Asia/Shanghai?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ENC(2TgNxhuTBazVWRIB2qmmFoSimggK6SVx)

# https://github.com/ulisesbocchio/jasypt-spring-boot
jasypt:
  encryptor:
    password: I'm very handsome