server:
  port: 8888
spring:
  profiles:
    active: db
  application:
    name: learn_project
easyopen:
  app-name: learn_easyOpen
  show-doc: true #设置api文档是否显示
  ignore-validate: true #设置忽略请求验证
  mono: true
