server:
  port: 8888
spring:
  profiles:
    active: db,mybatis,cache
  application:
    name: learn_project
easyopen:
  app-name: learn_easyOpen
  show-doc: true #设置api文档是否显示
  #ignore-validate: true #设置忽略请求验证
  mono: true
  doc-password: ENC(8B5qSFUPj6vB+lfFDLKjJg==)
  app-secret: #是map类型
    learn: learn_easyOpen
  timeout-seconds: 5 #设置超时时间